namespace WeddingPlanner.Api.Common;

/// <summary>
/// Bölüm 12-13: Yeni bir WeddingSpace oluşturulduğunda otomatik eklenen
/// varsayılan kategoriler ve örnek görevler. Kullanıcı bunları tamamen
/// özelleştirebilir (düzenleyebilir, silebilir, yeni ekleyebilir).
/// Kullanıcının verdiği kapsamlı "master liste" burada genel başlıklar
/// altında gruplanarak (alt kategori özelliği olmadan) temsil edilir.
/// </summary>
public static class DefaultWeddingData
{
    public static readonly (string Name, int Order)[] Categories =
    {
        ("Çeyiz", 0),
        ("Ev İhtiyaçları", 1),
        ("Ev Kurulumu", 2),
        ("Temizlik ve Ev Düzeni", 3),
        ("Kız İsteme", 4),
        ("Söz", 5),
        ("Nişan", 6),
        ("Bohça", 7),
        ("Kına", 8),
        ("Düğün", 9),
        ("Gelin Çiçeği ve Aksesuarları", 10),
        ("Düğün Hediyelikleri", 11),
        ("Resmi İşlemler", 12),
        ("Evi Taşıma ve Yerleşme", 13),
        ("Balayı", 14),
        ("Düğüne 1 Ay Kala", 15),
        ("Düğün Haftası", 16),
        ("Düğün Günü Acil Çanta", 17),
    };

    public static readonly (string CategoryName, string Title, decimal EstimatedPrice)[] SampleTasks =
    {
        // Çeyiz — Mutfak (Pişirme, Sofra, Mutfak Gereçleri, Saklama, Tekstil)
        ("Çeyiz", "Yemek Takımı", 8000m),
        ("Çeyiz", "Kahvaltı Takımı", 3500m),
        ("Çeyiz", "Tencere Seti", 12000m),
        ("Çeyiz", "Düdüklü Tencere", 3000m),
        ("Çeyiz", "Tava Seti (Sahan, Wok Dahil)", 2500m),
        ("Çeyiz", "Borcam Seti ve Güveç Kapları", 1500m),
        ("Çeyiz", "Fırın Tepsileri ve Kalıplar (Kek, Tart, Muffin)", 1200m),
        ("Çeyiz", "Çatal Kaşık Bıçak Seti", 2500m),
        ("Çeyiz", "Servis Tabakları ve Servis Kaşıkları", 1500m),
        ("Çeyiz", "Çerezlik ve Salata Servis Seti", 800m),
        ("Çeyiz", "Bardak Takımları (Su, Meşrubat, Çay, Kahve, Kupa)", 1500m),
        ("Çeyiz", "Kadeh ve Shot Bardağı Takımı", 1000m),
        ("Çeyiz", "Sürahi / Karaf ve Tepsi", 800m),
        ("Çeyiz", "Mutfak Bıçak Seti ve Kesme Tahtası", 1200m),
        ("Çeyiz", "Soyacak, Rende, Sıkacak Seti", 500m),
        ("Çeyiz", "Kevgir, Süzgeç, Maşa, Spatula, Kepçe Seti", 700m),
        ("Çeyiz", "Ölçü Kabı, Ölçü Kaşıkları, Mutfak Makası", 500m),
        ("Çeyiz", "Şişe / Konserve Açacağı ve Tirbuşon", 300m),
        ("Çeyiz", "Saklama Kabı Seti (Plastik + Cam)", 1500m),
        ("Çeyiz", "Baharatlık Seti, Yağdanlık, Sirkelik", 600m),
        ("Çeyiz", "Ekmek Kutusu ve Kurabiye / Bakliyat Kavanozları", 700m),
        ("Çeyiz", "Buzdolabı Düzenleyicileri", 500m),
        ("Çeyiz", "Mutfak Tekstili (Önlük, Fırın Eldiveni, Havlu)", 800m),
        ("Çeyiz", "Masa Örtüsü, Runner ve Amerikan Servis Seti", 1200m),

        // Çeyiz — Yatak Odası
        ("Çeyiz", "Yatak ve Baza", 25000m),
        ("Çeyiz", "Yorgan (Kışlık + Yazlık) ve Battaniye", 3000m),
        ("Çeyiz", "Alez / Yatak Koruyucu", 800m),
        ("Çeyiz", "Nevresim Takımı ve Lastikli Çarşaf Seti", 2800m),
        ("Çeyiz", "Yastık ve Ortopedik Yastık Seti", 2000m),
        ("Çeyiz", "Pike, Yatak Örtüsü, Dekoratif Yastıklar", 2000m),
        ("Çeyiz", "Elbise Askıları, Hurç, Çekmece Düzenleyicileri", 1000m),
        ("Çeyiz", "Takı ve Ayakkabı Organizeri", 800m),
        ("Çeyiz", "Perde", 4000m),
        ("Çeyiz", "Halı", 8000m),

        // Çeyiz — Banyo
        ("Çeyiz", "Banyo Havlu Seti (El, Yüz, Ayak, Misafir)", 1200m),
        ("Çeyiz", "Bornoz Seti ve Ev Terliği", 1800m),
        ("Çeyiz", "Banyo ve Tuvalet Paspası, Duş Perdesi", 800m),
        ("Çeyiz", "Sabunluk, Diş Fırçalık, Şampuanlık Seti", 500m),
        ("Çeyiz", "Çamaşır Sepeti ve Banyo Organizeri", 700m),
        ("Çeyiz", "Çöp Kovası ve Tuvalet Fırçası", 300m),

        // Ev İhtiyaçları — Beyaz Eşya ve Küçük Ev Aletleri
        ("Ev İhtiyaçları", "Buzdolabı", 35000m),
        ("Ev İhtiyaçları", "Çamaşır Makinesi", 18000m),
        ("Ev İhtiyaçları", "Bulaşık Makinesi", 16000m),
        ("Ev İhtiyaçları", "Fırın ve Ocak", 12000m),
        ("Ev İhtiyaçları", "Davlumbaz", 5000m),
        ("Ev İhtiyaçları", "Televizyon", 15000m),
        ("Ev İhtiyaçları", "Klima", 20000m),
        ("Ev İhtiyaçları", "Kombi / Şofben", 15000m),
        ("Ev İhtiyaçları", "Mikrodalga Fırın", 4000m),
        ("Ev İhtiyaçları", "Su Sebili", 2500m),
        ("Ev İhtiyaçları", "Airfryer", 3500m),
        ("Ev İhtiyaçları", "Robot Süpürge ve Dikey Süpürge", 8000m),
        ("Ev İhtiyaçları", "Çay Makinesi ve Türk Kahvesi Makinesi", 2000m),
        ("Ev İhtiyaçları", "Filtre Kahve / Espresso Makinesi", 3000m),
        ("Ev İhtiyaçları", "Kettle (Su Isıtıcısı)", 800m),
        ("Ev İhtiyaçları", "Tost Makinesi", 1000m),
        ("Ev İhtiyaçları", "Blender Seti", 1500m),
        ("Ev İhtiyaçları", "Mikser ve Mutfak Robotu", 3000m),
        ("Ev İhtiyaçları", "Buharlı Ütü ve Ütü Masası", 2500m),
        ("Ev İhtiyaçları", "Saç Kurutma Makinesi", 800m),

        // Ev Kurulumu — Mobilya ve Dekorasyon
        ("Ev Kurulumu", "Koltuk Takımı", 45000m),
        ("Ev Kurulumu", "TV Ünitesi", 6000m),
        ("Ev Kurulumu", "Yemek Masası ve Sandalye Takımı", 15000m),
        ("Ev Kurulumu", "Orta Sehpa", 3000m),
        ("Ev Kurulumu", "Yatak Odası Takımı", 30000m),
        ("Ev Kurulumu", "Gardırop", 12000m),
        ("Ev Kurulumu", "Komodin", 3000m),
        ("Ev Kurulumu", "Şifonyer", 7000m),
        ("Ev Kurulumu", "Ayakkabılık", 2000m),
        ("Ev Kurulumu", "Dresuar", 5000m),
        ("Ev Kurulumu", "Halı", 5000m),
        ("Ev Kurulumu", "Perde ve Tül", 4000m),
        ("Ev Kurulumu", "Avize", 2500m),
        ("Ev Kurulumu", "Lambader / Abajur", 1500m),
        ("Ev Kurulumu", "Ayna / Duvar Dekorasyonu", 1500m),
        ("Ev Kurulumu", "Dekoratif Objeler / Çiçek / Saksı", 1000m),

        // Temizlik ve Ev Düzeni
        ("Temizlik ve Ev Düzeni", "Elektrikli Süpürge", 6000m),
        ("Temizlik ve Ev Düzeni", "Mop ve Kova", 500m),
        ("Temizlik ve Ev Düzeni", "Temizlik Seti (Cam Silme, Toz Bezi, Mikrofiber Bez)", 500m),
        ("Temizlik ve Ev Düzeni", "Çamaşır Kurutmalık ve Mandal", 400m),
        ("Temizlik ve Ev Düzeni", "Ütü ve Ütü Masası", 2000m),
        ("Temizlik ve Ev Düzeni", "Çamaşır Sepeti", 400m),
        ("Temizlik ve Ev Düzeni", "Çöp Kovaları ve Çöp Poşetleri", 500m),
        ("Temizlik ve Ev Düzeni", "Genel Temizlik Ürünleri", 800m),

        // Kız İsteme
        ("Kız İsteme", "Kız İsteme Tarihi Belirleme ve Aileleri Bilgilendirme", 0m),
        ("Kız İsteme", "Kıyafet Seçimi", 3000m),
        ("Kız İsteme", "Ev Hazırlığı ve Misafir Listesi", 0m),
        ("Kız İsteme", "İkram Hazırlığı (Tatlı, Çikolata, Lokum, Kurabiye, Tuzlu İkramlıklar)", 1000m),
        ("Kız İsteme", "Çay / Kahve ve İçecekler", 500m),
        ("Kız İsteme", "Türk Kahvesi Sunum Seti (Fincan, Tepsi)", 500m),
        ("Kız İsteme", "Çiçek", 500m),
        ("Kız İsteme", "Yüzükler ve Yüzük Tepsisi", 3000m),
        ("Kız İsteme", "Kurdele ve Makas", 200m),
        ("Kız İsteme", "Anı Fotoğrafı Çekimi", 1500m),
        ("Kız İsteme", "Dekorasyon / Arka Fon", 500m),

        // Söz
        ("Söz", "Söz Mekanı / Ev Organizasyonu ve Konsept", 3000m),
        ("Söz", "Söz Masası, Çiçek ve Dekorasyon", 1000m),
        ("Söz", "Söz Yüzükleri", 5000m),
        ("Söz", "Söz Tepsisi, Kurdele, Makas", 500m),
        ("Söz", "Davetli Listesi", 0m),
        ("Söz", "Kıyafet ve Ayakkabı", 2500m),
        ("Söz", "Saç ve Makyaj", 1500m),
        ("Söz", "Çikolata ve Pasta", 1500m),
        ("Söz", "İkramlıklar", 800m),
        ("Söz", "Fotoğraf / Video Çekimi", 2000m),
        ("Söz", "Dijital Duyuru / Instagram Paylaşımı Tasarımı", 300m),

        // Nişan
        ("Nişan", "Nişan Mekanı (Salon / Restoran / Ev)", 40000m),
        ("Nişan", "Organizasyon Firması, Konsept, Arka Fon", 5000m),
        ("Nişan", "Masa Düzeni, Sandalye ve Süsleme", 3000m),
        ("Nişan", "Nişan Yüzükleri", 15000m),
        ("Nişan", "Yüzük Tepsisi, Kurdele, Makas", 500m),
        ("Nişan", "Nişan Bohçası", 2000m),
        ("Nişan", "Gelinlik / Kıyafet, Ayakkabı, Takı, Çanta", 8000m),
        ("Nişan", "Saç ve Makyaj", 3000m),
        ("Nişan", "Davetli Listesi ve Masa Planı", 0m),
        ("Nişan", "Davetiyeler (Basılı + Dijital)", 1500m),
        ("Nişan", "Hediyelik / İkram / Pasta", 2000m),
        ("Nişan", "Fotoğraf ve Video Çekimi", 10000m),
        ("Nişan", "Drone Çekimi ve Albüm", 3000m),
        ("Nişan", "Orkestra / DJ", 8000m),

        // Bohça — Gelin İçin
        ("Bohça", "Gelin İçin: Pijama, Sabahlık, Gecelik", 1500m),
        ("Bohça", "Gelin İçin: İç Çamaşırı, Çorap, Terlik, Bornoz, Havlu", 1500m),
        ("Bohça", "Gelin İçin: Parfüm, Deodorant, Duş ve Cilt Bakım Ürünleri", 1500m),
        ("Bohça", "Gelin İçin: Makyaj Ürünleri", 1500m),
        ("Bohça", "Gelin İçin: Çanta, Cüzdan, Takı, Saat, Aksesuar", 3000m),
        ("Bohça", "Gelin İçin: Seccade", 500m),
        // Bohça — Damat İçin
        ("Bohça", "Damat İçin: Pijama, Sabahlık, Gecelik", 1500m),
        ("Bohça", "Damat İçin: İç Çamaşırı, Çorap, Terlik, Bornoz, Havlu", 1500m),
        ("Bohça", "Damat İçin: Parfüm, Deodorant, Tıraş Seti, Cilt Bakım Ürünleri", 1500m),
        ("Bohça", "Damat İçin: Gömlek, Kravat, Kemer, Cüzdan, Saat, Ayakkabı", 3000m),
        ("Bohça", "Damat İçin: Seccade", 500m),
        // Bohça — Genel
        ("Bohça", "Kına Gecesi Kıyafetleri", 3000m),
        ("Bohça", "Takı", 4000m),
        ("Bohça", "Tatlı / Lokum", 1500m),
        ("Bohça", "Bohça Süslemesi / Organizasyonu", 1000m),
        ("Bohça", "Kişiye Özel Hediyeler", 1500m),

        // Kına
        ("Kına", "Kına Mekanı ve Organizasyon Firması", 25000m),
        ("Kına", "Konsept, Dekorasyon, Masa Süsleme, Sahne, Işıklandırma", 5000m),
        ("Kına", "Kına Gecesi Kıyafeti (Bindallı / Kaftan)", 3500m),
        ("Kına", "Kına Tacı ve Aksesuarları", 1000m),
        ("Kına", "Saç ve Makyaj", 3000m),
        ("Kına", "Kına Malzemeleri (Kına, Tepsi, Sepet, Mum, Fular, Eldiven, Kese)", 800m),
        ("Kına", "Kına Tepsisi ve Dağıtmalık Süslemesi", 1500m),
        ("Kına", "Davetli Listesi ve Davetiyeler", 1000m),
        ("Kına", "Hediyelik, İkramlıklar, İçecekler, Pasta", 2000m),
        ("Kına", "Fotoğraf Çekimi", 3000m),
        ("Kına", "Müzik / DJ (Giriş, Çıkarma, Oyun Havası, Halay Listesi)", 5000m),

        // Düğün
        ("Düğün", "Düğün Mekanı (Salon / Kır Düğünü / Otel / Restoran)", 150000m),
        ("Düğün", "Mekan Sözleşmesi, Kapora, Kalan Ödeme Takibi", 0m),
        ("Düğün", "Organizasyon Firması", 10000m),
        ("Düğün", "Masa Süslemesi, Sandalye Süslemesi, Gelin Masası", 5000m),
        ("Düğün", "Gelin Yolu, Sahne, Arka Fon, Çiçekler, Işıklandırma", 5000m),
        ("Düğün", "Müzik: DJ / Orkestra", 15000m),
        ("Düğün", "Müzik: İlk Dans, Giriş, Pasta ve Halay Müzikleri", 0m),
        ("Düğün", "Gelinlik ve Aksesuarları (Duvak, Takı, Çanta, Parfüm)", 15000m),
        ("Düğün", "Gelin Ayakkabısı ve Yedek Ayakkabı", 1500m),
        ("Düğün", "Damatlık, Gömlek, Kravat / Papyon", 8000m),
        ("Düğün", "Damat Ayakkabı, Kemer, Kol Düğmesi, Saat, Parfüm", 2000m),
        ("Düğün", "Gelin Saçı ve Makyajı, Manikür, Pedikür, Kaş, Cilt Bakımı", 4000m),
        ("Düğün", "Damat Saç ve Tıraşı", 500m),
        ("Düğün", "Davetli Listesi ve Masa Planı / Oturma Düzeni", 0m),
        ("Düğün", "Davetiye Tasarımı, Baskısı ve Dağıtımı", 3000m),
        ("Düğün", "Fotoğraf ve Video Çekimi", 20000m),
        ("Düğün", "Drone Çekimi, Save the Date, Dış Çekim", 5000m),
        ("Düğün", "Albüm Seçimi ve Video Klip", 3000m),
        ("Düğün", "Düğün Pastası ve Pasta Tadımı", 5000m),
        ("Düğün", "İkram Menüsü, Meşrubat, Kahve / Çay", 8000m),
        ("Düğün", "Gelin Arabası / VIP Transfer", 5000m),
        ("Düğün", "Nikah Memuru, Tarih, Başvuru ve Gerekli Belgeler", 0m),
        ("Düğün", "Şahitler ve Nikah Şekeri", 2000m),
        ("Düğün", "Nikah Defteri", 500m),
        ("Düğün", "Canlı Yayın / Sosyal Medya Paylaşımı", 1000m),

        // Gelin Çiçeği ve Aksesuarları
        ("Gelin Çiçeği ve Aksesuarları", "Gelin Buketi", 2000m),
        ("Gelin Çiçeği ve Aksesuarları", "Damat Yaka Çiçeği", 300m),
        ("Gelin Çiçeği ve Aksesuarları", "Nedime Çiçekleri", 1000m),
        ("Gelin Çiçeği ve Aksesuarları", "Gelin Tacı ve Saç Aksesuarı", 1500m),
        ("Gelin Çiçeği ve Aksesuarları", "Duvak", 1000m),
        ("Gelin Çiçeği ve Aksesuarları", "Takılar", 5000m),
        ("Gelin Çiçeği ve Aksesuarları", "Alyans ve Alyans Kutusu", 10000m),

        // Düğün Hediyelikleri
        ("Düğün Hediyelikleri", "Nikah Şekeri", 2000m),
        ("Düğün Hediyelikleri", "Kolonya", 1000m),
        ("Düğün Hediyelikleri", "Magnet / Mum / Çikolata / Lokum", 1500m),
        ("Düğün Hediyelikleri", "Özel Hediyelik", 2000m),
        ("Düğün Hediyelikleri", "Misafir Karşılama Hediyesi", 1500m),

        // Resmi İşlemler
        ("Resmi İşlemler", "Nikah Başvurusu ve Nikah Dairesi Randevusu", 0m),
        ("Resmi İşlemler", "Kimlik Kontrolü ve Fotoğraf", 0m),
        ("Resmi İşlemler", "Sağlık Raporu", 500m),
        ("Resmi İşlemler", "Şahitleri Belirleme", 0m),
        ("Resmi İşlemler", "Nikah Ücretini Ödeme", 0m),
        ("Resmi İşlemler", "Evlilik Sonrası Nüfus Cüzdanı İşlemleri", 0m),
        ("Resmi İşlemler", "Soyadı Değişikliği İşlemleri", 0m),
        ("Resmi İşlemler", "Adres Değişikliği", 0m),
        ("Resmi İşlemler", "Banka Bilgilerini Güncelleme / Ortak Hesap Açılışı", 0m),
        ("Resmi İşlemler", "Sigorta İşlemleri", 0m),
        ("Resmi İşlemler", "Gerekli Abonelikleri Düzenleme", 0m),
        ("Resmi İşlemler", "e-Devlet Evlilik Bildirimi Takibi", 0m),

        // Evi Taşıma ve Yerleşme
        ("Evi Taşıma ve Yerleşme", "Ev Temizliği / Derin Temizlik", 2000m),
        ("Evi Taşıma ve Yerleşme", "Mobilyaların ve Beyaz Eşyaların Teslim Alınması", 0m),
        ("Evi Taşıma ve Yerleşme", "İnternet Bağlatma", 500m),
        ("Evi Taşıma ve Yerleşme", "Elektrik, Su, Doğalgaz İşlemleri", 500m),
        ("Evi Taşıma ve Yerleşme", "Perdelerin Takılması ve Halıların Serilmesi", 0m),
        ("Evi Taşıma ve Yerleşme", "Mutfak, Gardırop, Banyo Yerleşimi", 0m),
        ("Evi Taşıma ve Yerleşme", "Temizlik Malzemelerinin Alınması", 500m),
        ("Evi Taşıma ve Yerleşme", "İlk Market Alışverişi", 1500m),

        // Balayı
        ("Balayı", "Balayı Destinasyonu Seçimi ve Tarih Belirleme", 0m),
        ("Balayı", "Uçak Bileti", 15000m),
        ("Balayı", "Otel Rezervasyonu ve Transfer", 25000m),
        ("Balayı", "Pasaport / Vize İşlemleri", 2000m),
        ("Balayı", "Seyahat Sigortası", 1000m),
        ("Balayı", "Bavul Hazırlığı (Kıyafet, Mayo, İç Çamaşırı, Pijama, Terlik)", 3000m),
        ("Balayı", "Kişisel Bakım Ürünleri (Diş Fırçası, Şampuan, Güneş Kremi, Makyaj)", 1000m),
        ("Balayı", "Teknoloji (Şarj Kablosu, Powerbank, Kamera, Adaptör)", 1500m),
        ("Balayı", "Yurt Dışı Hat / eSIM", 500m),
        ("Balayı", "Gezi Planı, Aktiviteler ve Özel Sürprizler (Spa, Tekne Turu)", 5000m),

        // Düğüne 1 Ay Kala (Son Kontrol)
        ("Düğüne 1 Ay Kala", "Gelinlik Son Provası", 0m),
        ("Düğüne 1 Ay Kala", "Damatlık Son Kontrolü", 0m),
        ("Düğüne 1 Ay Kala", "Alyansları Teslim Al", 0m),
        ("Düğüne 1 Ay Kala", "Nikah Belgelerini Kontrol Et", 0m),
        ("Düğüne 1 Ay Kala", "Davetli Listesini Kesinleştir", 0m),
        ("Düğüne 1 Ay Kala", "Masa Düzenini Kesinleştir", 0m),
        ("Düğüne 1 Ay Kala", "Mekanla Son Toplantıyı Yap", 0m),
        ("Düğüne 1 Ay Kala", "Organizasyon Firmasını Teyit Et", 0m),
        ("Düğüne 1 Ay Kala", "Fotoğrafçıyı Teyit Et", 0m),
        ("Düğüne 1 Ay Kala", "DJ / Orkestrayı Teyit Et", 0m),
        ("Düğüne 1 Ay Kala", "Kuaför Randevusunu Teyit Et", 0m),
        ("Düğüne 1 Ay Kala", "Makyaj Randevusunu Teyit Et", 0m),
        ("Düğüne 1 Ay Kala", "Balayı Rezervasyonlarını Kontrol Et", 0m),
        ("Düğüne 1 Ay Kala", "Uçuşları Kontrol Et", 0m),
        ("Düğüne 1 Ay Kala", "Otel Rezervasyonunu Kontrol Et", 0m),
        ("Düğüne 1 Ay Kala", "Düğün Ödemelerini Kontrol Et", 0m),
        ("Düğüne 1 Ay Kala", "Acil Durum Çantasını Hazırla", 0m),

        // Düğün Haftası (7 / 3 / 1 Gün Kala)
        ("Düğün Haftası", "7 Gün Kala: Mekanı, Organizasyon Firmasını ve Fotoğrafçıyı Tekrar Teyit Et", 0m),
        ("Düğün Haftası", "7 Gün Kala: Kuaförü Teyit Et ve Gelinlik Teslimini Kontrol Et", 0m),
        ("Düğün Haftası", "7 Gün Kala: Damatlığı ve Alyansları Hazırla", 0m),
        ("Düğün Haftası", "7 Gün Kala: Balayı Bavuluna Başla", 0m),
        ("Düğün Haftası", "3 Gün Kala: Çanta, Gelinlik Aksesuarları, Ayakkabı ve Takıları Hazırla", 0m),
        ("Düğün Haftası", "3 Gün Kala: Belgeleri ve Balayı Belgelerini Hazırla", 0m),
        ("Düğün Haftası", "3 Gün Kala: Ödemeleri Kontrol Et", 0m),
        ("Düğün Haftası", "1 Gün Kala: Telefonları ve Powerbank'i Şarj Et", 0m),
        ("Düğün Haftası", "1 Gün Kala: Alyansları, Gelinlik ve Damatlığı Son Kez Hazırla", 0m),
        ("Düğün Haftası", "1 Gün Kala: Balayı Bavulunu Tamamla", 0m),
        ("Düğün Haftası", "1 Gün Kala: Düğün Günü Sorumlusunu Belirle ve Tedarikçi Telefonlarını Hazırla", 0m),

        // Düğün Günü Acil Çanta
        ("Düğün Günü Acil Çanta", "İğne-İplik, Çengelli İğne, Çift Taraflı Bant, Mini Makas", 200m),
        ("Düğün Günü Acil Çanta", "Ağrı Kesici ve Yara Bandı", 100m),
        ("Düğün Günü Acil Çanta", "Islak ve Kuru Mendil", 100m),
        ("Düğün Günü Acil Çanta", "Deodorant, Parfüm, Pudra, Ruj", 300m),
        ("Düğün Günü Acil Çanta", "Saç Spreyi ve Tel Toka", 200m),
        ("Düğün Günü Acil Çanta", "Yedek Çorap ve Yedek Ayakkabı", 500m),
        ("Düğün Günü Acil Çanta", "Şarj Kablosu ve Powerbank", 500m),
        ("Düğün Günü Acil Çanta", "Su ve Atıştırmalık", 100m),
        ("Düğün Günü Acil Çanta", "Güvenlik İğnesi ve Leke Çıkarıcı Mendil", 100m),
    };
}
