namespace WeddingPlanner.Api.Common;

/// <summary>
/// Bölüm 12-13: Yeni bir WeddingSpace oluşturulduğunda otomatik eklenen
/// varsayılan kategoriler ve örnek görevler. Kullanıcı bunları tamamen
/// özelleştirebilir (düzenleyebilir, silebilir, yeni ekleyebilir).
/// Kapsamlı "master liste" burada daha az sayıda, geniş başlık altında
/// gruplanarak (alt kategori özelliği olmadan) temsil edilir.
/// </summary>
public static class DefaultWeddingData
{
    public static readonly (string Name, int Order)[] Categories =
    {
        ("Çeyiz", 0),
        ("Ev İhtiyaçları", 1),
        ("Kız İsteme, Söz ve Nişan", 2),
        ("Bohça", 3),
        ("Kına", 4),
        ("Düğün", 5),
        ("Resmi İşlemler", 6),
        ("Evi Taşıma ve Yerleşme", 7),
        ("Balayı", 8),
    };

    public static readonly (string CategoryName, string Title, decimal EstimatedPrice)[] SampleTasks =
    {
        // Çeyiz — Mutfak: Pişirme
        ("Çeyiz", "Tencere Seti", 12000m),
        ("Çeyiz", "Düdüklü Tencere", 3000m),
        ("Çeyiz", "Tava Seti", 1500m),
        ("Çeyiz", "Sahan Seti", 800m),
        ("Çeyiz", "Wok Tava", 700m),
        ("Çeyiz", "Borcam Seti", 900m),
        ("Çeyiz", "Fırın Tepsileri", 500m),
        ("Çeyiz", "Kek Kalıbı", 300m),
        ("Çeyiz", "Tart Kalıbı", 300m),
        ("Çeyiz", "Muffin Kalıbı", 250m),
        ("Çeyiz", "Güveç Kapları", 600m),

        // Çeyiz — Mutfak: Sofra
        ("Çeyiz", "Yemek Takımı", 8000m),
        ("Çeyiz", "Kahvaltı Takımı", 3500m),
        ("Çeyiz", "Çatal Kaşık Bıçak Seti", 2500m),
        ("Çeyiz", "Servis Kaşıkları", 400m),
        ("Çeyiz", "Servis Tabakları", 800m),
        ("Çeyiz", "Çerezlik", 300m),
        ("Çeyiz", "Salata Kasesi", 400m),
        ("Çeyiz", "Salata Servis Seti", 400m),
        ("Çeyiz", "Meşrubat Bardakları", 500m),
        ("Çeyiz", "Su Bardakları", 400m),
        ("Çeyiz", "Çay Bardağı Seti", 500m),
        ("Çeyiz", "Kahve Fincanı Seti", 600m),
        ("Çeyiz", "Kupa", 300m),
        ("Çeyiz", "Rakı / Bira / Şarap Kadehi", 700m),
        ("Çeyiz", "Shot Bardağı", 300m),
        ("Çeyiz", "Sürahi", 400m),
        ("Çeyiz", "Karaf", 500m),
        ("Çeyiz", "Tepsi", 400m),
        ("Çeyiz", "Kahvaltılık Kaseler", 400m),

        // Çeyiz — Mutfak: Mutfak Gereçleri
        ("Çeyiz", "Mutfak Bıçak Seti", 1200m),
        ("Çeyiz", "Kesme Tahtası", 400m),
        ("Çeyiz", "Soyacak", 150m),
        ("Çeyiz", "Rende", 150m),
        ("Çeyiz", "Sarımsak Ezici", 150m),
        ("Çeyiz", "Limon Sıkacağı", 150m),
        ("Çeyiz", "Narenciye Sıkacağı", 250m),
        ("Çeyiz", "Kevgir", 200m),
        ("Çeyiz", "Süzgeç", 200m),
        ("Çeyiz", "Maşa", 150m),
        ("Çeyiz", "Spatula", 150m),
        ("Çeyiz", "Kepçe", 150m),
        ("Çeyiz", "Çırpıcı", 200m),
        ("Çeyiz", "Ölçü Kabı", 200m),
        ("Çeyiz", "Ölçü Kaşıkları", 150m),
        ("Çeyiz", "Mutfak Makası", 200m),
        ("Çeyiz", "Havan", 300m),
        ("Çeyiz", "Şişe Açacağı", 100m),
        ("Çeyiz", "Konserve Açacağı", 100m),
        ("Çeyiz", "Tirbuşon", 200m),

        // Çeyiz — Mutfak: Saklama
        ("Çeyiz", "Saklama Kabı Seti", 1000m),
        ("Çeyiz", "Cam Saklama Kabı", 800m),
        ("Çeyiz", "Baharatlık Seti", 500m),
        ("Çeyiz", "Yağdanlık", 200m),
        ("Çeyiz", "Sirkelik", 200m),
        ("Çeyiz", "Ekmek Kutusu", 500m),
        ("Çeyiz", "Kurabiye Kavanozu", 400m),
        ("Çeyiz", "Bakliyat Kavanozları", 600m),
        ("Çeyiz", "Buzdolabı Düzenleyicileri", 500m),
        ("Çeyiz", "Streç Film", 100m),
        ("Çeyiz", "Alüminyum Folyo", 100m),
        ("Çeyiz", "Kilitli Poşet", 100m),

        // Çeyiz — Mutfak: Mutfak Tekstili
        ("Çeyiz", "Mutfak Havluları", 300m),
        ("Çeyiz", "Fırın Eldiveni", 200m),
        ("Çeyiz", "Fırın Önlüğü", 300m),
        ("Çeyiz", "Masa Örtüsü", 500m),
        ("Çeyiz", "Runner", 300m),
        ("Çeyiz", "Amerikan Servis", 400m),
        ("Çeyiz", "Peçeteler", 200m),

        // Çeyiz — Yatak Odası: Yatak
        ("Çeyiz", "Yatak", 20000m),
        ("Çeyiz", "Baza", 6000m),
        ("Çeyiz", "Başlık", 3000m),
        ("Çeyiz", "Yastık", 500m),
        ("Çeyiz", "Ortopedik Yastık", 1200m),
        ("Çeyiz", "Yorgan", 2000m),
        ("Çeyiz", "Yazlık Yorgan", 1500m),
        ("Çeyiz", "Battaniye", 800m),
        ("Çeyiz", "Alez", 500m),
        ("Çeyiz", "Yatak Koruyucu", 500m),

        // Çeyiz — Yatak Odası: Nevresim
        ("Çeyiz", "Nevresim Takımı", 2800m),
        ("Çeyiz", "Çarşaf", 600m),
        ("Çeyiz", "Lastikli Çarşaf", 700m),
        ("Çeyiz", "Yastık Kılıfı", 300m),
        ("Çeyiz", "Pike", 1200m),
        ("Çeyiz", "Yatak Örtüsü", 1500m),
        ("Çeyiz", "Dekoratif Yastıklar", 500m),

        // Çeyiz — Yatak Odası: Düzen
        ("Çeyiz", "Elbise Askıları", 300m),
        ("Çeyiz", "Hurç", 800m),
        ("Çeyiz", "Çekmece Düzenleyicileri", 400m),
        ("Çeyiz", "Takı Organizeri", 500m),
        ("Çeyiz", "Ayakkabı Düzenleyici", 400m),
        ("Çeyiz", "Perde", 4000m),
        ("Çeyiz", "Halı", 8000m),

        // Çeyiz — Banyo
        ("Çeyiz", "Banyo Havlu Seti", 800m),
        ("Çeyiz", "El Havlusu", 300m),
        ("Çeyiz", "Yüz Havlusu", 300m),
        ("Çeyiz", "Ayak Havlusu", 300m),
        ("Çeyiz", "Bornoz", 900m),
        ("Çeyiz", "Ev Terliği", 400m),
        ("Çeyiz", "Banyo Paspası", 300m),
        ("Çeyiz", "Tuvalet Paspası", 200m),
        ("Çeyiz", "Duş Perdesi", 400m),
        ("Çeyiz", "Sabunluk", 150m),
        ("Çeyiz", "Diş Fırçalık", 150m),
        ("Çeyiz", "Şampuanlık", 200m),
        ("Çeyiz", "Çöp Kovası", 200m),
        ("Çeyiz", "Tuvalet Fırçası", 150m),
        ("Çeyiz", "Çamaşır Sepeti", 500m),
        ("Çeyiz", "Banyo Organizeri", 400m),
        ("Çeyiz", "Misafir Havluları", 400m),

        // Ev İhtiyaçları — Beyaz Eşya, Küçük Ev Aletleri, Mobilya, Dekorasyon, Temizlik
        ("Ev İhtiyaçları", "Buzdolabı", 35000m),
        ("Ev İhtiyaçları", "Çamaşır Makinesi", 18000m),
        ("Ev İhtiyaçları", "Bulaşık Makinesi", 16000m),
        ("Ev İhtiyaçları", "Fırın ve Ocak", 12000m),
        ("Ev İhtiyaçları", "Davlumbaz", 5000m),
        ("Ev İhtiyaçları", "Televizyon", 15000m),
        ("Ev İhtiyaçları", "Klima", 20000m),
        ("Ev İhtiyaçları", "Kombi / Şofben", 15000m),
        ("Ev İhtiyaçları", "Mikrodalga Fırın", 4000m),
        ("Ev İhtiyaçları", "Su Sebili", 2500m),
        ("Ev İhtiyaçları", "Airfryer", 3500m),
        ("Ev İhtiyaçları", "Robot Süpürge ve Dikey Süpürge", 8000m),
        ("Ev İhtiyaçları", "Çay Makinesi ve Türk Kahvesi Makinesi", 2000m),
        ("Ev İhtiyaçları", "Filtre Kahve / Espresso Makinesi", 3000m),
        ("Ev İhtiyaçları", "Kettle (Su Isıtıcısı)", 800m),
        ("Ev İhtiyaçları", "Tost Makinesi", 1000m),
        ("Ev İhtiyaçları", "Blender Seti", 1500m),
        ("Ev İhtiyaçları", "Mikser ve Mutfak Robotu", 3000m),
        ("Ev İhtiyaçları", "Buharlı Ütü ve Ütü Masası", 2500m),
        ("Ev İhtiyaçları", "Saç Kurutma Makinesi", 800m),
        ("Ev İhtiyaçları", "Koltuk Takımı", 45000m),
        ("Ev İhtiyaçları", "TV Ünitesi", 6000m),
        ("Ev İhtiyaçları", "Yemek Masası ve Sandalye Takımı", 15000m),
        ("Ev İhtiyaçları", "Orta Sehpa", 3000m),
        ("Ev İhtiyaçları", "Yatak Odası Takımı", 30000m),
        ("Ev İhtiyaçları", "Gardırop", 12000m),
        ("Ev İhtiyaçları", "Komodin", 3000m),
        ("Ev İhtiyaçları", "Şifonyer", 7000m),
        ("Ev İhtiyaçları", "Ayakkabılık", 2000m),
        ("Ev İhtiyaçları", "Dresuar", 5000m),
        ("Ev İhtiyaçları", "Halı", 5000m),
        ("Ev İhtiyaçları", "Perde ve Tül", 4000m),
        ("Ev İhtiyaçları", "Avize", 2500m),
        ("Ev İhtiyaçları", "Lambader / Abajur", 1500m),
        ("Ev İhtiyaçları", "Ayna / Duvar Dekorasyonu", 1500m),
        ("Ev İhtiyaçları", "Dekoratif Objeler / Çiçek / Saksı", 1000m),
        ("Ev İhtiyaçları", "Elektrikli Süpürge", 6000m),
        ("Ev İhtiyaçları", "Mop ve Kova", 500m),
        ("Ev İhtiyaçları", "Temizlik Seti (Cam Silme, Toz Bezi, Mikrofiber Bez)", 500m),
        ("Ev İhtiyaçları", "Çamaşır Kurutmalık ve Mandal", 400m),
        ("Ev İhtiyaçları", "Çamaşır Sepeti", 400m),
        ("Ev İhtiyaçları", "Çöp Kovaları ve Çöp Poşetleri", 500m),
        ("Ev İhtiyaçları", "Genel Temizlik Ürünleri", 800m),

        // Kız İsteme, Söz ve Nişan
        ("Kız İsteme, Söz ve Nişan", "Kız İsteme Tarihi Belirleme ve Aileleri Bilgilendirme", 0m),
        ("Kız İsteme, Söz ve Nişan", "Kız İsteme: Kıyafet Seçimi", 3000m),
        ("Kız İsteme, Söz ve Nişan", "Kız İsteme: Ev Hazırlığı ve Misafir Listesi", 0m),
        ("Kız İsteme, Söz ve Nişan", "Kız İsteme: İkram Hazırlığı (Tatlı, Çikolata, Lokum, Kurabiye)", 1000m),
        ("Kız İsteme, Söz ve Nişan", "Kız İsteme: Türk Kahvesi Sunum Seti (Fincan, Tepsi)", 500m),
        ("Kız İsteme, Söz ve Nişan", "Kız İsteme: Çiçek", 500m),
        ("Kız İsteme, Söz ve Nişan", "Kız İsteme: Yüzükler ve Yüzük Tepsisi", 3000m),
        ("Kız İsteme, Söz ve Nişan", "Kız İsteme: Anı Fotoğrafı Çekimi", 1500m),
        ("Kız İsteme, Söz ve Nişan", "Söz: Mekan / Ev Organizasyonu ve Konsept", 3000m),
        ("Kız İsteme, Söz ve Nişan", "Söz: Masa, Çiçek ve Dekorasyon", 1000m),
        ("Kız İsteme, Söz ve Nişan", "Söz: Söz Yüzükleri", 5000m),
        ("Kız İsteme, Söz ve Nişan", "Söz: Tepsi, Kurdele, Makas", 500m),
        ("Kız İsteme, Söz ve Nişan", "Söz: Davetli Listesi", 0m),
        ("Kız İsteme, Söz ve Nişan", "Söz: Kıyafet ve Ayakkabı", 2500m),
        ("Kız İsteme, Söz ve Nişan", "Söz: Saç ve Makyaj", 1500m),
        ("Kız İsteme, Söz ve Nişan", "Söz: Çikolata ve Pasta", 1500m),
        ("Kız İsteme, Söz ve Nişan", "Söz: Fotoğraf / Video Çekimi", 2000m),
        ("Kız İsteme, Söz ve Nişan", "Söz: Dijital Duyuru / Instagram Paylaşımı Tasarımı", 300m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Mekan (Salon / Restoran / Ev)", 40000m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Organizasyon Firması, Konsept, Arka Fon", 5000m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Masa Düzeni, Sandalye ve Süsleme", 3000m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Nişan Yüzükleri", 15000m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Yüzük Tepsisi, Kurdele, Makas", 500m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Nişan Bohçası", 2000m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Gelinlik / Kıyafet, Ayakkabı, Takı, Çanta", 8000m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Saç ve Makyaj", 3000m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Davetli Listesi ve Masa Planı", 0m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Davetiyeler (Basılı + Dijital)", 1500m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Hediyelik / İkram / Pasta", 2000m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Fotoğraf ve Video Çekimi", 10000m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Drone Çekimi ve Albüm", 3000m),
        ("Kız İsteme, Söz ve Nişan", "Nişan: Orkestra / DJ", 8000m),

        // Bohça — Gelin İçin
        ("Bohça", "Gelin İçin: Pijama, Sabahlık, Gecelik", 1500m),
        ("Bohça", "Gelin İçin: İç Çamaşırı, Çorap, Terlik, Bornoz, Havlu", 1500m),
        ("Bohça", "Gelin İçin: Parfüm, Deodorant, Duş ve Cilt Bakım Ürünleri", 1500m),
        ("Bohça", "Gelin İçin: Makyaj Ürünleri", 1500m),
        ("Bohça", "Gelin İçin: Çanta, Cüzdan, Takı, Saat, Aksesuar", 3000m),
        ("Bohça", "Gelin İçin: Seccade", 500m),
        // Bohça — Damat İçin
        ("Bohça", "Damat İçin: Pijama, Sabahlık, Gecelik", 1500m),
        ("Bohça", "Damat İçin: İç Çamaşırı, Çorap, Terlik, Bornoz, Havlu", 1500m),
        ("Bohça", "Damat İçin: Parfüm, Deodorant, Tıraş Seti, Cilt Bakım Ürünleri", 1500m),
        ("Bohça", "Damat İçin: Gömlek, Kravat, Kemer, Cüzdan, Saat, Ayakkabı", 3000m),
        ("Bohça", "Damat İçin: Seccade", 500m),
        // Bohça — Genel
        ("Bohça", "Kına Gecesi Kıyafetleri", 3000m),
        ("Bohça", "Takı", 4000m),
        ("Bohça", "Tatlı / Lokum", 1500m),
        ("Bohça", "Bohça Süslemesi / Organizasyonu", 1000m),
        ("Bohça", "Kişiye Özel Hediyeler", 1500m),

        // Kına
        ("Kına", "Kına Mekanı ve Organizasyon Firması", 25000m),
        ("Kına", "Konsept, Dekorasyon, Masa Süsleme, Sahne, Işıklandırma", 5000m),
        ("Kına", "Kına Gecesi Kıyafeti (Bindallı / Kaftan)", 3500m),
        ("Kına", "Kına Tacı ve Aksesuarları", 1000m),
        ("Kına", "Saç ve Makyaj", 3000m),
        ("Kına", "Kına Malzemeleri (Kına, Tepsi, Sepet, Mum, Fular, Eldiven, Kese)", 800m),
        ("Kına", "Kına Tepsisi ve Dağıtmalık Süslemesi", 1500m),
        ("Kına", "Davetli Listesi ve Davetiyeler", 1000m),
        ("Kına", "Hediyelik, İkramlıklar, İçecekler, Pasta", 2000m),
        ("Kına", "Fotoğraf Çekimi", 3000m),
        ("Kına", "Müzik / DJ (Giriş, Çıkarma, Oyun Havası, Halay Listesi)", 5000m),

        // Düğün (kendisi + Gelin Çiçeği/Aksesuar + Hediyelikler + 1 Ay Kala + Düğün Haftası + Acil Çanta)
        ("Düğün", "Düğün Mekanı (Salon / Kır Düğünü / Otel / Restoran)", 150000m),
        ("Düğün", "Mekan Sözleşmesi, Kapora, Kalan Ödeme Takibi", 0m),
        ("Düğün", "Organizasyon Firması", 10000m),
        ("Düğün", "Masa Süslemesi, Sandalye Süslemesi, Gelin Masası", 5000m),
        ("Düğün", "Gelin Yolu, Sahne, Arka Fon, Çiçekler, Işıklandırma", 5000m),
        ("Düğün", "Müzik: DJ / Orkestra", 15000m),
        ("Düğün", "Müzik: İlk Dans, Giriş, Pasta ve Halay Müzikleri", 0m),
        ("Düğün", "Gelinlik ve Aksesuarları (Duvak, Takı, Çanta, Parfüm)", 15000m),
        ("Düğün", "Gelin Ayakkabısı ve Yedek Ayakkabı", 1500m),
        ("Düğün", "Damatlık, Gömlek, Kravat / Papyon", 8000m),
        ("Düğün", "Damat Ayakkabı, Kemer, Kol Düğmesi, Saat, Parfüm", 2000m),
        ("Düğün", "Gelin Saçı ve Makyajı, Manikür, Pedikür, Kaş, Cilt Bakımı", 4000m),
        ("Düğün", "Damat Saç ve Tıraşı", 500m),
        ("Düğün", "Davetli Listesi ve Masa Planı / Oturma Düzeni", 0m),
        ("Düğün", "Davetiye Tasarımı, Baskısı ve Dağıtımı", 3000m),
        ("Düğün", "Fotoğraf ve Video Çekimi", 20000m),
        ("Düğün", "Drone Çekimi, Save the Date, Dış Çekim", 5000m),
        ("Düğün", "Albüm Seçimi ve Video Klip", 3000m),
        ("Düğün", "Düğün Pastası ve Pasta Tadımı", 5000m),
        ("Düğün", "İkram Menüsü, Meşrubat, Kahve / Çay", 8000m),
        ("Düğün", "Gelin Arabası / VIP Transfer", 5000m),
        ("Düğün", "Nikah Memuru, Tarih, Başvuru ve Gerekli Belgeler", 0m),
        ("Düğün", "Şahitler ve Nikah Şekeri", 2000m),
        ("Düğün", "Nikah Defteri", 500m),
        ("Düğün", "Canlı Yayın / Sosyal Medya Paylaşımı", 1000m),
        ("Düğün", "Gelin Buketi ve Damat Yaka Çiçeği", 2000m),
        ("Düğün", "Nedime Çiçekleri", 1000m),
        ("Düğün", "Gelin Tacı, Saç Aksesuarı, Duvak", 2000m),
        ("Düğün", "Takılar", 5000m),
        ("Düğün", "Alyans ve Alyans Kutusu", 10000m),
        ("Düğün", "Nikah Şekeri, Kolonya, Magnet, Mum (Hediyelik)", 2500m),
        ("Düğün", "Misafir Karşılama Hediyesi ve Özel Hediyelik", 2500m),
        ("Düğün", "1 Ay Kala: Gelinlik / Damatlık Son Provası ve Kontrolü", 0m),
        ("Düğün", "1 Ay Kala: Alyansları Teslim Al, Nikah Belgelerini Kontrol Et", 0m),
        ("Düğün", "1 Ay Kala: Davetli Listesi ve Masa Düzenini Kesinleştir", 0m),
        ("Düğün", "1 Ay Kala: Mekan, Organizasyon, Fotoğrafçı, DJ/Orkestra Teyidi", 0m),
        ("Düğün", "1 Ay Kala: Kuaför ve Makyaj Randevusunu Teyit Et", 0m),
        ("Düğün", "1 Ay Kala: Balayı Rezervasyonları, Uçuş ve Otel Kontrolü", 0m),
        ("Düğün", "1 Ay Kala: Düğün Ödemelerini Kontrol Et", 0m),
        ("Düğün", "7 Gün Kala: Tüm Tedarikçileri (Mekan, Fotoğrafçı, Kuaför) Son Kez Teyit Et", 0m),
        ("Düğün", "7 Gün Kala: Damatlığı, Alyansları ve Balayı Bavuluna Hazırlığı Başlat", 0m),
        ("Düğün", "3 Gün Kala: Çanta, Aksesuar, Ayakkabı, Takı ve Belgeleri Hazırla", 0m),
        ("Düğün", "3 Gün Kala: Ödemeleri Son Kez Kontrol Et", 0m),
        ("Düğün", "1 Gün Kala: Telefon/Powerbank Şarjı, Son Hazırlıklar ve Sorumlu Ataması", 0m),
        ("Düğün", "Acil Çanta: Dikiş Seti, Ağrı Kesici, Yara Bandı, Mendil", 300m),
        ("Düğün", "Acil Çanta: Deodorant, Parfüm, Pudra, Ruj, Saç Spreyi", 300m),
        ("Düğün", "Acil Çanta: Yedek Çorap / Ayakkabı, Şarj Kablosu, Powerbank", 500m),
        ("Düğün", "Acil Çanta: Su, Atıştırmalık, Güvenlik İğnesi, Leke Çıkarıcı", 100m),

        // Resmi İşlemler
        ("Resmi İşlemler", "Nikah Başvurusu ve Nikah Dairesi Randevusu", 0m),
        ("Resmi İşlemler", "Kimlik Kontrolü ve Fotoğraf", 0m),
        ("Resmi İşlemler", "Sağlık Raporu", 500m),
        ("Resmi İşlemler", "Şahitleri Belirleme", 0m),
        ("Resmi İşlemler", "Nikah Ücretini Ödeme", 0m),
        ("Resmi İşlemler", "Evlilik Sonrası Nüfus Cüzdanı İşlemleri", 0m),
        ("Resmi İşlemler", "Soyadı Değişikliği İşlemleri", 0m),
        ("Resmi İşlemler", "Adres Değişikliği", 0m),
        ("Resmi İşlemler", "Banka Bilgilerini Güncelleme / Ortak Hesap Açılışı", 0m),
        ("Resmi İşlemler", "Sigorta İşlemleri", 0m),
        ("Resmi İşlemler", "Gerekli Abonelikleri Düzenleme", 0m),
        ("Resmi İşlemler", "e-Devlet Evlilik Bildirimi Takibi", 0m),

        // Evi Taşıma ve Yerleşme
        ("Evi Taşıma ve Yerleşme", "Ev Temizliği / Derin Temizlik", 2000m),
        ("Evi Taşıma ve Yerleşme", "Mobilyaların ve Beyaz Eşyaların Teslim Alınması", 0m),
        ("Evi Taşıma ve Yerleşme", "İnternet Bağlatma", 500m),
        ("Evi Taşıma ve Yerleşme", "Elektrik, Su, Doğalgaz İşlemleri", 500m),
        ("Evi Taşıma ve Yerleşme", "Perdelerin Takılması ve Halıların Serilmesi", 0m),
        ("Evi Taşıma ve Yerleşme", "Mutfak, Gardırop, Banyo Yerleşimi", 0m),
        ("Evi Taşıma ve Yerleşme", "Temizlik Malzemelerinin Alınması", 500m),
        ("Evi Taşıma ve Yerleşme", "İlk Market Alışverişi", 1500m),

        // Balayı
        ("Balayı", "Balayı Destinasyonu Seçimi ve Tarih Belirleme", 0m),
        ("Balayı", "Uçak Bileti", 15000m),
        ("Balayı", "Otel Rezervasyonu ve Transfer", 25000m),
        ("Balayı", "Pasaport / Vize İşlemleri", 2000m),
        ("Balayı", "Seyahat Sigortası", 1000m),
        ("Balayı", "Bavul Hazırlığı (Kıyafet, Mayo, İç Çamaşırı, Pijama, Terlik)", 3000m),
        ("Balayı", "Kişisel Bakım Ürünleri (Diş Fırçası, Şampuan, Güneş Kremi, Makyaj)", 1000m),
        ("Balayı", "Teknoloji (Şarj Kablosu, Powerbank, Kamera, Adaptör)", 1500m),
        ("Balayı", "Yurt Dışı Hat / eSIM", 500m),
        ("Balayı", "Gezi Planı, Aktiviteler ve Özel Sürprizler (Spa, Tekne Turu)", 5000m),
    };
}
